export  const numbers ={
  "battleMusicMinvolume" : 0.2,
  "zero" : 0 ,
  "heroDmg" : 50 ,
  "monsterDmg" : 50 ,
  "gameOverTime" : 4 ,
  "monsterPoints" : 20 ,
  "endOfGameFiled" : window.innerWidth - 130 ,
  "playerInitialCoordinateX" : 10 ,
  "playerInitialCoordinateY" : window.innerHeight - 300 ,
  "playerGoBack" : 5 ,
  "playerGo" : 10 ,
  "playerSpellInitialCoordinateX" : 70 ,
  "playerSpellInitialCoordinateY" : window.innerHeight - 300 ,
  "monsterSpellInitialCoordinateX" : window.innerWidth-(window.innerWidth / 3) ,
  "monsterSpellInitialCoordinateY" : window.innerHeight - 300 ,
  "monsterSpellFly" : 20 ,
  "playerSpellFly" : 20 ,
  "playerCastBorder" :  window.innerWidth - 100
}
